coercion_strategy: null
created_at: '2025-06-12T13:53:53.644806Z'
description: Some custom Description
display_name: null
effective_type: null
fk_target_field_id: null
has_field_values: null
semantic_type: null
visibility_type: null
serdes/meta:
- id: My Database
  model: Database
- id: Schemaless Table
  model: Table
- id: Some Field
  model: Field
- id: '1'
  model: FieldUserSettings
