name: e2e-sdk-sample-apps

services:
  node-sample-app:
    profiles:
      - node-sample-app
    image: sdk-node-app:latest
    build:
      context: ../../../.
      dockerfile: e2e/runner/embedding-sdk-sample-apps/Dockerfile.nodejs
    # this lets the containerized app talk to the host machine
    extra_hosts:
      - "host-metabase:host-gateway"
    ports:
      - 3100:3100
      - 9091:9091
    environment:
      MB_PREMIUM_EMBEDDING_TOKEN: ${MB_PREMIUM_EMBEDDING_TOKEN}

  # other sample apps are just other services with distinct tags
  # apps that need multiple containers can just use the same profile
