name: Prepare front-end environment
inputs:
  node-version:
    description: "The version of Node.js to use, overriding .nvmrc"
    required: false
runs:
  using: "composite"
  steps:
    - name: Prepare Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }} # this overrides, if present
        node-version-file: ".nvmrc"

    - name: Get cache week
      id: cache-week
      run: echo "week=$(date +%Y-W%U)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Check to see if dependencies should be cached
      if: ${{ contains(github.event.head_commit.message, '[ci nocache]') }}
      run: |
        echo "Commit message includes [ci nocache]; dependencies will NOT be cached"
        yarn cache clean
      shell: bash
    - name: Get M2 cache (week-based)
      uses: actions/cache@v4
      if: ${{ !contains(github.event.head_commit.message, '[ci nocache]') }}
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-cljs-${{ steps.cache-week.outputs.week }}
        restore-keys: |
          ${{ runner.os }}-m2-cljs-
          ${{ runner.os }}-m2-cljs-${{ hashFiles('**/shadow-cljs.edn', '**/deps.edn') }}
          ${{ runner.os }}-m2-

    - name: Get node_modules cache (week-based)
      uses: actions/cache@v4
      id: node-modules-cache
      if: ${{ !contains(github.event.head_commit.message, '[ci nocache]') }}
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ steps.cache-week.outputs.week }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
          ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock', '**/patches/*.patch', 'package.json') }}

    - run: yarn install --frozen-lockfile --prefer-offline
      shell: bash
