name: Auto E2E Stress Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.cy.spec.js"
      - "**/*.cy.spec.ts"
      - "**/*.spec.js"
      - "**/*.spec.ts"
jobs:
  detect-and-run-tests:
    name: Detect and Run Stress Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      # Needed to trigger workflows
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          # Install GitHub CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find and run affected tests
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          HEAD_REF=${{ github.head_ref || github.ref_name }}

          echo "Running cypress-test-finder against base branch: $BASE_BRANCH"
          echo "Using head ref: $HEAD_REF"

          # Run with --execute to automatically trigger workflows
          node cypress-test-finder.js --base=$BASE_BRANCH --ref=$HEAD_REF --execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            try {
              // Get workflow run URL to link in the comment
              const runUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;

              // Create comment content
              let commentBody = `## 🔄 E2E Stress Tests Triggered\n\n`;
              commentBody += `I've automatically triggered stress tests for the Cypress tests affected by this PR.\n\n`;
              commentBody += `[View details in the workflow run](${runUrl})\n\n`;
              commentBody += `Each affected test will run 20 times to ensure it's stable and not flaky.\n`;
              commentBody += `Check the [Actions tab](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions) for individual test workflow runs.`;

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });

              console.log('Added PR comment about triggered stress tests');
            } catch (error) {
              console.error('Error adding PR comment:', error);
            }
