name: E2E Tests (Cypress Split with Full Setup)

on:
  push:
    branches:
      - "master"
      - "release-**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  files-changed:
    name: Check which files changed
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    outputs:
      e2e_all: ${{ steps.changes.outputs.e2e_all }}
    steps:
      - uses: actions/checkout@v4
      - name: Test which files changed
        uses: dorny/paths-filter@v3.0.0
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-paths.yaml

  e2e-matrix-builder:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.e2e-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate matrix for E2E tests
        id: e2e-matrix
        uses: ./.github/actions/build-e2e-matrix

  build:
    needs: [files-changed, e2e-matrix-builder]
    if: |
      !cancelled() &&
      github.event.pull_request.draft == false &&
      needs.e2e-matrix-builder.result == 'success' &&
      needs.files-changed.outputs.e2e_all == 'true'
    runs-on: ubuntu-22.04
    timeout-minutes: 25
    strategy:
      matrix:
        edition: [oss, ee]
    env:
      MB_EDITION: ${{ matrix.edition }}
      INTERACTIVE: false
      SKIP_LICENSES: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
        with:
          m2-cache-key: uberjar
          java-version: 11

      - name: Build uberjar with ./bin/build.sh
        run: ./bin/build.sh

      - name: Prepare uberjar artifact
        uses: ./.github/actions/prepare-uberjar-artifact
        with:
          name: metabase-${{ matrix.edition }}-${{ github.event.pull_request.head.sha || github.sha }}-uberjar

  e2e-tests-split:
    needs: [build, e2e-matrix-builder]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.e2e-matrix-builder.outputs.matrix) }}

    services:
      metabase:
        image: metabase/metabase:latest
        ports:
          - 4000:3000
        options: >-
          --health-cmd="curl --fail http://localhost:3000/api/health || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Prepare Docker containers
      - name: Prepare Docker containers
        uses: ./.github/actions/e2e-prepare-containers
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          maildev: true
          openldap: ${{ matrix.containers == 0 }}
          postgres: ${{ matrix.containers != 2 }}
          mysql: ${{ matrix.containers != 3 }}
          mongo: ${{ matrix.containers == 3 }}
          webhook: true

      # 3. Retrieve uberjar artifact
      - name: Retrieve uberjar artifact
        uses: actions/download-artifact@v4
        with:
          name: metabase-${{ matrix.edition }}-${{ github.event.pull_request.head.sha || github.sha }}-uberjar

      # 4. Extract version info
      - name: Get the version info
        run: |
          jar xf target/uberjar/metabase.jar version.properties
          mv version.properties resources/

      # 5. Prepare front-end environment
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend

      # 6. Prepare JDK environment
      - name: Prepare JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"

      # 7. Prepare Cypress environment
      - name: Prepare Cypress environment
        id: cypress-prep
        uses: ./.github/actions/prepare-cypress

      # 8. Run Snowplow microservice
      - name: Run Snowplow micro
        uses: ./.github/actions/run-snowplow-micro

      # 9. Run Cypress tests with `cypress-split`
      - name: Run split Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          config-file: e2e/support/cypress.config.js
        env:
          SPLIT: ${{ strategy.job-total }} # Total parallel jobs
          SPLIT_INDEX: ${{ matrix.containers }} # Index of this job
          CYPRESS_CI: true
          MB_EDITION: ${{ matrix.edition }}
          DISPLAY: ""
          QA_DB_ENABLED: true
          CYPRESS_ALL_FEATURES_TOKEN: ${{ secrets.ENTERPRISE_TOKEN }}
          CYPRESS_NO_FEATURES_TOKEN: ${{ secrets.E2E_STARTER_TOKEN }}
          CYPRESS_PULL_REQUEST_ID: ${{ github.event.pull_request.number || '' }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title || github.event.head_commit.message || github.event.head.sha }}
          MB_SNOWPLOW_AVAILABLE: true
          MB_SNOWPLOW_URL: "http://localhost:9090"

      # 10. Upload test results
      - name: Upload Test Results
        uses: ./.github/actions/upload-test-results
        if: always()
        with:
          input-path: ./target/junit
          output-name: cypress-split-${{ matrix.containers }}
          bucket: ${{ vars.AWS_S3_TEST_RESULTS_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_TEST_RESULTS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TEST_RESULTS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          trunk-api-token: ${{ secrets.TRUNK_API_TOKEN }}

      # 11. Upload Cypress artifacts
      - name: Upload Cypress Artifacts (on failure)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-split-artifacts-${{ matrix.containers }}
          path: |
            ./cypress
            ./logs/test.log
          if-no-files-found: ignore
