name: E2E Tests (Cypress Split)

on:
  push:
    branches:
      - "master"
      - "release-**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e-tests-split:
    # We'll run 3 parallel copies of this job
    # each with its own ephemeral container
    name: e2e-tests-split
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # pick how many parallel containers you want
        containers: [0, 1, 2, 4, 5, 6, 7, 8, 9]

    # services is defined at the job level
    # each parallel job has its own container, not shared
    services:
      metabase:
        image: metabase/metabase:latest
        ports:
          - 4000:3000
        options: >-
          --health-cmd="curl --fail http://localhost:3000/api/health || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    steps:
      # ---------------------------------------------------
      # 1) Checkout your repo, install deps, etc.
      # ---------------------------------------------------
      - name: Check out code
        uses: actions/checkout@v4

      - name: Prepare environment (Node, Yarn, etc.)
        uses: ./.github/actions/prepare-frontend

      # If you have a built uberjar artifact, you can download it here
      # - name: Retrieve uberjar artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: metabase-oss-<sha>-uberjar

      - name: Wait for Metabase service
        run: |
          echo "Waiting ~15s for Metabase to pass healthcheck..."
          sleep 15

      # ---------------------------------------------------
      # 2) Prepare Cypress environment
      # ---------------------------------------------------
      - name: Prepare Cypress environment
        id: cypress-prep
        uses: ./.github/actions/prepare-cypress

      # ---------------------------------------------------
      # 3) Run Cypress with cypress-split
      #    We pass SPLIT / SPLIT_INDEX from the matrix
      # ---------------------------------------------------
      - name: Run split Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          # By default, cypress-io/github-action runs "cypress run"
          # cypress-split (in cypress.config.js) will see SPLIT and SPLIT_INDEX
          # and only run a portion of the specs
        env:
          SPLIT: ${{ strategy.job-total }} # total # of parallel containers
          SPLIT_INDEX: ${{ matrix.containers }} # 0..2 for 3 containers

      # ---------------------------------------------------
      # 4) Upload test results, artifacts
      # ---------------------------------------------------
      - name: Upload Test Results
        uses: ./.github/actions/upload-test-results
        if: always()
        with:
          input-path: ./target/junit
          output-name: cypress-split-${{ matrix.containers }}
          bucket: ${{ vars.AWS_S3_TEST_RESULTS_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_TEST_RESULTS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TEST_RESULTS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          trunk-api-token: ${{ secrets.TRUNK_API_TOKEN }}

      - name: Upload Cypress Artifacts (on failure)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-split-artifacts-${{ matrix.containers }}
          path: |
            ./cypress
            ./logs/test.log
          if-no-files-found: ignore
