name: External PR Label

on:
  pull_request:

jobs:
  external-pr-label:
    # if: ${{ github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Add External label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: | # js
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['External']
            });
