name: Manual Cache Bust

on:
  workflow_dispatch:
    inputs:
      cache_types:
        description: 'Cache types to bust'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'
          - 'clojure'
          - 'nodejs'
          - 'unified'
          - 'clojure,nodejs'
          - 'clojure,unified'
          - 'nodejs,unified'
      week_offset:
        description: 'Week offset (0=current week, 1=last week, etc.)'
        required: false
        default: '0'
        type: string
      dry_run:
        description: 'Dry run - only show what would be deleted without actually deleting'
        required: false
        default: false
        type: boolean

jobs:
  manual-cache-bust:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Calculate target week
        id: target-week
        run: |
          WEEK_OFFSET=${{ github.event.inputs.week_offset || '0' }}

          if [ "$WEEK_OFFSET" = "0" ]; then
            TARGET_WEEK=$(date +%Y-W%U)
          else
            # Calculate week with offset
            TARGET_DATE=$(date -d "$WEEK_OFFSET week ago" +%Y-%m-%d)
            TARGET_WEEK=$(date -d "$TARGET_DATE" +%Y-W%U)
          fi

          echo "week=$TARGET_WEEK" >> $GITHUB_OUTPUT
          echo "🎯 Target week: $TARGET_WEEK"

      - name: Bust caches
        uses: ./.github/actions/bust-cache
        with:
          cache-types: ${{ github.event.inputs.cache_types }}
          target-week: ${{ steps.target-week.outputs.week }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: ${{ github.event.inputs.dry_run || 'false' }}
          context: "Manual Cache Bust"

      # Summary generated by bust-cache action
