name: Auto-Optimize Docs PNG Images

on:
  push:
    paths:
      - 'docs/**/*.png'

jobs:
  optimize-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install pngcrush
      run: |
        sudo apt-get update
        sudo apt-get install -y pngcrush

    - name: Get changed PNG files
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        files: |
          docs/**/*.png

    - name: Optimize changed PNG files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Optimizing PNG files with pngcrush..."
        echo "Branch:" $(git_current_branch)
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "Processing: $file"
          before_size=$(stat -c%s "$file")
          # Use pngcrush with maximum lossless compression settings
          # -rem alla removes all ancillary chunks (metadata)
          # -brute tries all filter types and compression levels
          # -ow overwrites the original file
          pngcrush -rem alla -brute -ow "$file"
          after_size=$(stat -c%s "$file")
          echo "  > Before: ${before_size} bytes, After: ${after_size} bytes"
        done
        echo "Optimization complete"

    - name: Check for changes after optimization
      if: steps.changed-files.outputs.any_changed == 'true'
      id: check_changes
      run: |
        git add ${{ steps.changed-files.outputs.all_changed_files }}
        if git diff --quiet --cached; then
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          echo "No changes detected after optimization"
        else
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
          echo "Changes detected after optimization"
          git diff --cached --stat
        fi

    - name: Commit optimized images
      if: steps.changed-files.outputs.any_changed == 'true' && steps.check_changes.outputs.has_changes == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.METABASE_AUTOMATION_USER_TOKEN }}
      run: |
        git config --global user.email "github-automation@metabase.com"
        git config --global user.name "Metabase Automation"
        git add docs/**/*.png
        git commit -m "Auto-optimize PNG images with pngcrush"
        git push
        echo 'Files optimized:'
        echo ${{ steps.changed-files.outputs.all_changed_files }}
        echo 'Applied: pngcrush -rem alla -brute -ow'

    - name: Output summary
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        if [ "${{ steps.check_changes.outputs.has_changes }}" = "false" ]; then
          echo "PNG files were already optimized - no changes needed"
        else
          echo "PNG files optimized and committed successfully"
        fi
