name: Privacy Checker PR Reporter

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      # First, checkout the repository
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Prepare backend environment
        uses: ./.github/actions/prepare-backend
        with:
          m2-cache-key: privacy-reporter
      - name: Run privacy reporter script
        id: script
        run: |
          clojure -X:dev:drivers:build:build-dev:build-test metabase.private-things-test/privacy-report
          # echo 'check it:'
          # cat privacy_report.txt
          # echo '------'
          {
          echo 'MULTILINE_CONTENT<<EOF'
          cat privacy_report.txt
          echo EOF
          } >> "$GITHUB_ENV"

      # Post the comment using github-script
      - name: Post comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MULTILINE_CONTENT
            });
