name: Privacy Checker PR Reporter

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      # First, checkout the repository
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
      - name: Run privacy reporter script
        id: script
        run: |
          clojure -X:dev:drivers:build:build-dev:build-test metabase.private-things-test/privacy-report
          echo "MULTILINE<<EOF" >> $GITHUB_OUTPUT
          cat privacy_report.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Post the comment using github-script
      - name: Post comment
        uses: actions/github-script@v7
        with:
          script: |
            const message = process.env.SCRIPT_OUTPUT;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
        env:
          SCRIPT_OUTPUT: ${{ steps.script.outputs.message }}
