name: Privacy Checker PR Reporter

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      # First, checkout the repository
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install clj
        uses: ./.github/actions/prepare-backend
      - name: Run privacy reporter script
        id: script
        run: |
          clojure -X:dev:drivers:build:build-dev:build-test metabase.private-things-test/privacy-report
          {
          echo 'MULTILINE_CONTENT<<EOF'
          cat privacy_report.txt
          echo 'EOF'
          } >> $GITHUB_ENV

      # Post the comment using github-script
      - name: Post comment
        uses: actions/github-script@v7
        env:
          MULTILINE_CONTENT: ${{ env.MULTILINE_CONTENT }}
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MULTILINE_CONTENT
            });
