name: Re-run Flaky Workflows

on:
  workflow_run:
    workflows: [Run tests]
    types: [completed]

jobs:
  should-rerun:
    name: Check if re-run is needed
    # Do not re-run scheduled workflow runs
    if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event != 'schedule'
    runs-on: ubuntu-latest
    outputs:
      should-rerun: ${{ steps.check.outputs.result }}
    steps:
    - uses: actions/github-script@v7
      id: check
      with:
        result-encoding: string
        script: | # js
          const RERUN_BRANCHES = ["master", "release-x"];
          const branchName = context.payload.workflow_run.head_branch;

          console.log({ branchName });

          const isRerunBranch = RERUN_BRANCHES.some(branch => branchName.startsWith(branch));

          if (isRerunBranch) {
            console.log(`Re-running workflow for branch: ${branchName}`);
            return true;
          }

          // check if there are any open pull requests for the branch
          const { data: pullRequests } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo : context.repo.repo,
            state: "open",
            head: `${context.owner.repo}:${branchName}`,
          });

          // if auto-merge is enabled, let's auto-rerun
          const hasAutoMergeEnabled = pullRequests.some(pr => !!pr.auto_merge);

          return hasAutoMergeEnabled;

  rerun-on-failure:
    needs: [should-rerun]
    if: needs.should-rerun.outputs.should-rerun == 'true'
    name: 'Re-run ''${{ github.event.workflow_run.name }}'' workflow'
    runs-on: ubuntu-22.04
    env:
      BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
      AUTHOR_NAME: ${{ github.event.workflow_run.head_commit.author.name }}
    steps:
      - name: Generate job summary
        run: |
          echo "# ${{ github.event.workflow_run.name }} workflow failed! :x:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View the failed run attempt (#${{ github.event.workflow_run.run_attempt }}) using the following link:" >> $GITHUB_STEP_SUMMARY
          echo "${{ github.event.workflow_run.html_url }}" >> $GITHUB_STEP_SUMMARY

      - uses: actions/setup-node@v4
        with:
          node-version: lts/Jod # 22.x.x
      - run: npm install @slack/web-api
      - name: Trigger a re-run
        uses: actions/github-script@v7
        with:
          script: | # js
            const MAX_ATTEMPTS = 1;
            const ATTEMPT = "${{ github.event.workflow_run.run_attempt }}";
            const FAILED_RUN_URL = "${{ github.event.workflow_run.html_url }}";
            const FAILED_RUN_NAME = "${{ github.event.workflow_run.name }}";
            const BREAKING_COMMIT = "${{ github.event.workflow_run.head_sha }}";
            const AUTHOR = process.env.AUTHOR_NAME;
            const BRANCH = process.env.BRANCH_NAME;

            if (ATTEMPT <= MAX_ATTEMPTS) {
              github.rest.actions.reRunWorkflowFailedJobs({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: ${{ github.event.workflow_run.id }},
              });
            } else if (BRANCH.includes('master') || BRANCH.includes('release-x')) {
              // notify slack of repeated failure
              const { WebClient } = require('@slack/web-api');
              const slack = new WebClient('${{ secrets.SLACK_BOT_TOKEN }}');

              // find out which jobs failed
              const { owner, repo } = context.repo;

              const jobInfo = await github.rest.actions.listJobsForWorkflowRun({
                owner,
                repo,
                run_id: ${{ github.event.workflow_run.id }},
                per_page: 100,
              });

              const failedJobs = jobInfo.data.jobs
                .filter(job => job.status === "completed" && job.conclusion === "failure" && !job.name.includes("-tests-result"));

              // don't bother slack if only the flaky job failed
              if (failedJobs.every(job => job.name.toLowerCase().includes("flaky"))) {
                return;
              }

              const failedJobsList = failedJobs.map(job => ({
                "type": "rich_text_section",
                "elements": [
                  {
                    "type": "link",
                    "text": job.name,
                    "url": job.html_url,
                  }
                ]
              }));

              await slack.chat.postMessage({
                channel: 'engineering-ci',
                text: 'Failing tests',
                blocks: [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": `:warning: CI is failing on ${BRANCH}`,
                      "emoji": true,
                    }
                  },
                ],
                attachments: [{
                  color: BRANCH === 'master' ? '#f85149' : "#ffce33",
                  blocks: [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": `Commit <https://github.com/metabase/metabase/commit/${BREAKING_COMMIT}|${BREAKING_COMMIT.slice(0,7)}> by ${AUTHOR} has failing <${FAILED_RUN_URL}|${FAILED_RUN_NAME}> tests on <https://github.com/${owner}/${repo}/commits/${BRANCH}|\`${BRANCH}\`>`
                      },
                    },
                    {
                      "type": "rich_text",
                      "block_id": "block1",
                      "elements": [
                        {
                          "type": "rich_text_list",
                          "style": "bullet",
                          "elements": failedJobsList,
                        },
                      ],
                    }
                  ]
                }]
              });
            }
