name: Run tests

on:
  push:
    branches:
      - "master"
      - "release-**"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  files-changed:
    name: Check which files changed
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      RUN_ALL: ${{ contains(github.pull_request.head_commit.message, '[run all]') || contains(github.push.head_commit.message, '[run all]') }}
    outputs:
      e2e_all: ${{ steps.changes.outputs.e2e_all || env.RUN_ALL }}
      backend_all: ${{ steps.changes.outputs.backend_all || env.RUN_ALL }}
      frontend_all: ${{ steps.changes.outputs.frontend_all || env.RUN_ALL }}
      frontend_sources: ${{ steps.changes.outputs.frontend_sources || env.RUN_ALL }}
    steps:
      - name: test
        run: | # bash
          echo "env ${{ env.RUN_ALL }}"
          echo "head_commit ${{ github.pull_request.head_commit.message }}"
      - uses: actions/checkout@v4
        if: ${{ !env.RUN_ALL }}
      - name: Test which files changed
        if: ${{ !env.RUN_ALL }}
        uses: dorny/paths-filter@v3.0.0
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-paths.yaml
      - name: Run all tests
        if: ${{ env.RUN_ALL }}
        run: |
          echo "Running all tests"

  static-viz-files-changed:
    name: Check whether static-viz files changed
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    env:
      RUN_ALL: ${{ contains(github.pull_request.head_commit.message, '[run all]') || contains(github.push.head_commit.message, '[run all]') }}
    outputs:
      static_viz: ${{ steps.static_viz.outputs.static_viz || env.RUN_ALL }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
        with:
          m2-cache-key: "files-changed"
      - name: Build static-viz frontend
        run: yarn build-static-viz
      - name: Upload Static Viz Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-viz-bundle-${{ github.sha }}
          path: resources/frontend_client/app/dist

      - name: Check for static viz changes
        uses: dorny/paths-filter@v3.0.0
        id: static_viz
        with:
          token: ${{ github.token }}
          filters: .github/static-viz-sources.yaml

  backend-tests:
    if: ${{ !cancelled() }}
    needs: [files-changed, static-viz-files-changed]
    uses: ./.github/workflows/backend.yml
    secrets: inherit
    with:
      skip: ${{ needs.files-changed.outputs.backend_all != 'true' && needs.static-viz-files-changed.outputs.static_viz != 'true' }}

  driver-tests:
    needs: files-changed
    uses: ./.github/workflows/drivers.yml
    secrets: inherit
    with:
      skip: ${{ needs.files-changed.outputs.backend_all != 'true' }}

  frontend-tests:
    needs: files-changed
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
    with:
      skip: ${{ needs.files-changed.outputs.frontend_all != 'true' }}

  e2e-tests:
    needs: files-changed
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
    with:
      skip: ${{ needs.files-changed.outputs.e2e_all != 'true' }}
